Updates
NREL/ReferenceHybridSystemDesigns pull request #2
Opened 2024-11-19 18:13 UTC by jaredthomas68

This PR updates the reference designs to work with FLORIS v4, HOPP v3.0, GreenHEART v0.1.3, and ORBIT v1.1

2024-11-25 20:10 UTC, kbrunik requested changes
Looks like some files were unintentionally added. Once those are a removed and a few small changes are made I think this should be good to go.

2024-11-25 20:10 UTC, kbrunik commented on reference-systems/03-gulf-of-mexico-hydrogen/greenHEART/03-gulf_of_mexico-hydrogen.py
> +        plant_design_scenario=3,
Looks like you sequentially go up in plant design per scenario. I think we should either keep them all as 1 or have the onshore configuration be 1 and the offshore configuration be 2 since the topology doesn't change for each location otherwise and I think it's a little confusing.

2024-11-25 20:10 UTC, kbrunik commented on reference-systems/05-california-hydrogen/greenHEART/input-files/floris/floris_input_osw_15MW.yaml
>  floris_version: v3.0.0
Update version to `floris_version: v4.0.0`

2024-11-25 20:10 UTC, kbrunik commented on reference-systems/04-new-york-bight-hydrogen/greenHEART/input-files/floris/floris_input_osw_15MW.yaml
>  floris_version: v3.0.0
update floris version to `floris_version: v4.0.0`

2024-11-25 20:10 UTC, kbrunik commented on reference-systems/03-gulf-of-mexico-hydrogen/greenHEART/input-files/floris/floris_input_osw_17MW.yaml
>  floris_version: v3.0.0
update floris version to `floris_version: v4.0.0`

2024-11-25 20:10 UTC, kbrunik commented on reference-systems/01-minnesota-steel/greenHEART/input-files/floris/floris_input_lbw_6MW.yaml
>  floris_version: v3.0.0
update floris version to `floris_version: v4.0.0`

2024-11-25 20:10 UTC, kbrunik commented on reference-systems/02-texas-ammonia/greenHEART/input-files/floris/floris_input_lbw_6MW.yaml
>  floris_version: v3.0.0
update floris version to `floris_version: v4.0.0`

2024-11-25 20:10 UTC, kbrunik commented on reference-systems/05-california-hydrogen/greenHEART/input-files/plant/default_fin_config.yaml
> +  om_fixed: [0]
The default file here looks different than the other default files, this one looks perhaps more up to date?

2024-11-25 20:10 UTC, kbrunik commented on tools/generate_plots.py
Are you trying to include this `tools` dir?

2024-11-26 15:41 UTC, jaredthomas68 commented on reference-systems/02-texas-ammonia/greenHEART/02-texas-ammonia.py
> +        plant_design_scenario=2,
I did this so output files have numbering that matches the reference number

2024-11-26 15:48 UTC, jaredthomas68 commented on reference-systems/03-gulf-of-mexico-hydrogen/greenHEART/log/hybrid_systems_2024-11-11T16.36.09.679027.log
Silly mistake on my part. Thanks.

2024-11-26 15:49 UTC, jaredthomas68 commented on reference-systems/03-gulf-of-mexico-hydrogen/greenHEART/input-files/turbines/osw_17MW_v3.yaml
Done

2024-11-26 15:50 UTC, jaredthomas68 commented on reference-systems/03-gulf-of-mexico-hydrogen/greenHEART/post-process.py
I debated this. I've been writing these for my work on the plants but I think they could be useful to others. I'm up to discussion here.

2024-11-26 15:52 UTC, jaredthomas68 commented on reference-systems/02-texas-ammonia/greenHEART/input-files/floris/floris_input_lbw_6MW.yaml
>  floris_version: v3.0.0
Done

2024-11-26 15:52 UTC, jaredthomas68 commented on reference-systems/01-minnesota-steel/greenHEART/input-files/floris/floris_input_lbw_6MW.yaml
>  floris_version: v3.0.0
Done

2024-11-26 15:52 UTC, jaredthomas68 commented on reference-systems/03-gulf-of-mexico-hydrogen/greenHEART/input-files/floris/floris_input_osw_17MW.yaml
>  floris_version: v3.0.0
Done

2024-11-26 15:52 UTC, jaredthomas68 commented on tools/generate_plots.py
Yes

2024-11-26 15:56 UTC, kbrunik commented on reference-systems/03-gulf-of-mexico-hydrogen/greenHEART/post-process.py
I think I'd rather have the post-processing added to GreenHEART and these stay as just the designs

2024-11-26 15:56 UTC, jaredthomas68 commented on reference-systems/05-california-hydrogen/greenHEART/input-files/plant/default_fin_config.yaml
> +  om_fixed: [0]
Just using brackets to make the list instead of hyphens. I made the same adjustment to all the other fin files

2024-11-26 16:00 UTC, jaredthomas68 commented on reference-systems/03-gulf-of-mexico-hydrogen/greenHEART/speed_dir_data.csv
Done

2024-11-26 16:01 UTC, kbrunik commented on tools/generate_tables.py
> +# def get_state_from_lat_long(latitude, longitude):
Can we either delete the commented code or uncomment it?

2024-11-26 16:01 UTC, jaredthomas68 commented on reference-systems/04-new-york-bight-hydrogen/greenHEART/log/hybrid_systems_2024-11-12T10.20.47.953320.log
Done

2024-11-26 16:03 UTC, jaredthomas68 commented on reference-systems/04-new-york-bight-hydrogen/greenHEART/input-files/turbines/osw_15MW_v3.yaml
Done

2024-11-26 16:03 UTC, jaredthomas68 commented on reference-systems/04-new-york-bight-hydrogen/greenHEART/post-process.py
I think so

2024-11-26 16:03 UTC, jaredthomas68 commented on reference-systems/04-new-york-bight-hydrogen/greenHEART/speed_dir_data.csv
done

2024-11-26 16:05 UTC, jaredthomas68 commented on reference-systems/03-gulf-of-mexico-hydrogen/greenHEART/03-gulf_of_mexico-hydrogen.py
> +        plant_design_scenario=3,
I disagree here, but we can discuss. The output files use the scenario number but not the reference design number. I would like to keep them matching the reference design so there are no output files that are exactly the same name between the reference designs. We can discuss more if you feel strongly about this.

2024-11-26 16:05 UTC, jaredthomas68 commented on reference-systems/05-california-hydrogen/greenHEART/input-files/floris/floris_input_osw_15MW.yaml
>  floris_version: v3.0.0
done

2024-11-26 16:05 UTC, jaredthomas68 commented on reference-systems/04-new-york-bight-hydrogen/greenHEART/input-files/floris/floris_input_osw_15MW.yaml
>  floris_version: v3.0.0
done

2024-11-26 16:08 UTC, jaredthomas68 commented on reference-systems/03-gulf_of_mexico-hydrogen/greenHEART/input-files/plant/default_fin_config.yaml
When I run `git log --follow FILE` I see the full history. Can you specify what you see missing?

2024-11-26 16:09 UTC, jaredthomas68 commented on reference-systems/04-new_york-hydrogen/greenHEART/input-files/plant/default_fin_config.yaml
When I run `git log --follow FILE` I see the full history. Can you specify what you see missing?

2024-11-26 16:11 UTC, jaredthomas68 commented on tools/generate_tables.py
> +# def get_state_from_lat_long(latitude, longitude):
Removed

2024-11-26 16:18 UTC, kbrunik commented on reference-systems/03-gulf_of_mexico-hydrogen/greenHEART/input-files/plant/default_fin_config.yaml
Curious, it just looks weird on the files changed section like you deleted it and then added a new file versus the moved icon. Not a big deal if it looks fine on your end.

2024-11-26 16:22 UTC, kbrunik commented on reference-systems/03-gulf-of-mexico-hydrogen/greenHEART/03-gulf_of_mexico-hydrogen.py
> +        plant_design_scenario=3,
I'm fine with them increasing sequentially if it makes the outputs/post-processing easier. It does feel a bit incongruent since they're the same designs but I think it's a GreenHEART issues not reference design issue.

2024-11-26 18:10 UTC, jaredthomas68 commented on reference-systems/03-gulf-of-mexico-hydrogen/greenHEART/post-process.py
The reason I put it in here is because the post-processing is specific to the repo - pulling results from all the designs into tables and plots, so putting it in GreenHEART won't work/would not be useful

2024-11-26 18:11 UTC, jaredthomas68 commented on reference-systems/03-gulf-of-mexico-hydrogen/greenHEART/03-gulf_of_mexico-hydrogen.py
> +        plant_design_scenario=3,
I agree

2024-11-26 18:36 UTC, jaredthomas68 commented on reference-systems/03-gulf-of-mexico-hydrogen/greenHEART/post-process.py
I had the wrong thing on my mind here. The function in this file could be put in GreenHEART. I'll do that. The tools directory is what is specific to this repo

2024-11-26 18:44 UTC, jaredthomas68 commented on reference-systems/03-gulf-of-mexico-hydrogen/greenHEART/post-process.py
Looking at these again, they are pretty specific and will take quite a bit of work to generalize that I don't think is worth it right now. I don't like having the duplicate code in each directory though. I can just keep this in my own project files for now.

2024-11-26 18:50 UTC, jaredthomas68 commented on reference-systems/03-gulf-of-mexico-hydrogen/greenHEART/post-process.py
Done

2024-11-26 18:50 UTC, kbrunik approved these changes

2024-11-26 18:51 UTC, merged