Fin update
NREL/ReferenceHybridSystemDesigns pull request #4
Opened 2024-11-21 23:22 UTC by jaredthomas68

This PR updates the financial parameters for both HOPP and GreenHEART to be location specific for each reference design location. This PR should be reviewed and merged after #2 and #3

2024-11-26 20:52 UTC, kbrunik requested changes
Okay I figured I'd leave some overall comments rather than commenting on each little thing:

1.  Add which tab from 2024 ATB the values came from i.e. "Offshore Wind", "Land-Based Wind"
2. I see 2022 ATB still on comments, lets update those to 2024 ATB values or fix the comment
3. Generally going over the comments again, it seems like some should be site specific but say H2A and H2FAST defaults.
4. Do we want to include URLs to where some of the site specific numbers are coming from?

2024-11-26 20:52 UTC, kbrunik commented on reference-systems/01-minnesota-steel/greenHEART/input-files/plant/default_fin_config.yaml
> +  state_tax_rate: 9.8
Do we want to include sources for these values that are location specific?

2024-11-26 20:52 UTC, kbrunik commented on reference-systems/02-texas-ammonia/greenHEART/input-files/plant/greenheart_config_onshore_tx.yaml
> +  property_tax: 0.0147  # percent of CAPEX # combined with property insurance then between H2A and H2FAST defaults
Was this not available for Texas?

2024-11-26 20:52 UTC, kbrunik commented on reference-systems/02-texas-ammonia/greenHEART/input-files/plant/greenheart_config_onshore_tx.yaml
> +  total_income_tax_rate: 0.21 # 0.257 tax rate in 2022 atb baseline workbook
Was this not available for Texas?

Is this tax rate from the 2024 ATB workbook?

2024-11-26 20:52 UTC, kbrunik commented on reference-systems/02-texas-ammonia/greenHEART/input-files/plant/greenheart_config_onshore_tx.yaml
> +  sales_tax_rate: 0.082
What's this from?

2024-11-26 20:52 UTC, kbrunik commented on reference-systems/04-new-york-bight-hydrogen/greenHEART/input-files/plant/default_fin_config.yaml
> +  sales_tax_rate_state: 8.20 # average combined state and local sales tax in NJ
Is NJ the same as Texas?

2024-11-26 20:52 UTC, kbrunik commented on reference-systems/03-gulf-of-mexico-hydrogen/greenHEART/input-files/plant/default_fin_config.yaml
> +  real_discount_rate: 0.063 # nominal return based on 2024 ATB basline workbook
Update line to include`with 0% inflation, real and nominal rates are equal` and which tab on the workbook it came from

2024-11-26 20:52 UTC, kbrunik commented on reference-systems/05-california-hydrogen/greenHEART/input-files/plant/default_fin_config.yaml
> +  real_discount_rate: 0.063 # nominal return based on 2024 ATB basline workbook
Update line to `real_discount_rate: 0.063 # nominal return based on 2024 ATB baseline workbook - with 0% inflation, real and nominal rates are equal`

2024-11-26 20:52 UTC, kbrunik commented on reference-systems/01-minnesota-steel/greenHEART/input-files/plant/default_fin_config.yaml
> +  property_tax_rate: 1.18
Where is this from?

2024-11-26 20:52 UTC, kbrunik commented on reference-systems/03-gulf-of-mexico-hydrogen/greenHEART/input-files/plant/default_fin_config.yaml
> +  state_tax_rate: 0.0
Add where `state_tax_rate` and `property_tax_rate` are from

2024-11-26 20:52 UTC, kbrunik commented on reference-systems/05-california-hydrogen/greenHEART/input-files/plant/greenheart_config_offshore_ca.yaml
> +  property_tax: 0.0071  # percent of CAPEX # combined with property insurance then between H2A and H2FAST defaults
This doesn't seem like it's from H2A and H2FAST?

2024-12-12 04:16 UTC, jaredthomas68 commented
> Okay I figured I'd leave some overall comments rather than commenting on each little thing:
> 
> 1. Add which tab from 2024 ATB the values came from i.e. "Offshore Wind", "Land-Based Wind"
> 2. I see 2022 ATB still on comments, lets update those to 2024 ATB values or fix the comment
> 3. Generally going over the comments again, it seems like some should be site specific but say H2A and H2FAST defaults.
> 4. Do we want to include URLs to where some of the site specific numbers are coming from?

I believe I have addressed all of your comments. Thank you for your feedback.

2024-12-12 13:48 UTC, kbrunik approved these changes
Just a few comment that would be good to address before merging. Thanks for all of the added detail!

2024-12-12 13:48 UTC, kbrunik commented on reference-systems/01-minnesota-steel/greenHEART/input-files/plant/greenheart_config_onshore_mn.yaml
> +  depreciation_period: 5 # years - as specified by the IRS MACRS schedule for wind and solar https://www.irs.gov/publications/p946#en_US_2020_publink1000107507
And battery?

2024-12-12 13:48 UTC, kbrunik commented on reference-systems/01-minnesota-steel/greenHEART/input-files/plant/default_fin_config.yaml
> +  real_discount_rate: 9.0 # nominal return based on 2024 ATB baseline workbook for land-based wind - with 0% inflation, real and nominal rates are equal
Presumably you are using the values for cost year 2030 and the moderate case? Could be good to add that as well

2024-12-12 18:37 UTC, merged